atualizando o  teste de coverage

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -45,6 +45,12 @@ jobs:
           New-Item -Path .\.sonar\scanner -ItemType Directory
           dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
 
+      - name: Install Dotnet Coverage
+        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+        shell: powershell
+        run: |
+          dotnet tool install dotnet-coverage --tool-path .\.sonar\scanner
+
       - name: Restore dependencies
         shell: powershell
         run: |
@@ -62,14 +68,27 @@ jobs:
           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
       - name: Verify Coverage File
-          shell: powershell
+          shell: bash
           run: |
-            dotnet sonarscanner begin /k:"<sonar-project-key>"
-            /d:sonar.token="<sonar-token>"
-            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
-            dotnet build --no-incremental
-            dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
-            dotnet sonarscanner end /d:sonar.token="<sonar-token>"
+            echo "Searching for coverage file..."
+            file=$(find ./TestResults -name "coverage.opencover.xml" | head -n 1)
+            if [ -z "$file" ]; then
+              echo "Coverage file not found!"
+              exit 1
+            else
+              echo "Found coverage file at $file"
+              exit 0
+
+            - name: Coverage test
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        shell: powershell
+        run: |
+          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Viniciusmendes21_API_Iquirium" /o:"viniciusmendes21" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="TestResults/coverage.opencover.xml"
+          dotnet build ./SampleWebApi.sln
+          .\.sonar\scanner\dotnet-coverage collect --output TestResults/coverage.opencover.xml
+          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
       - name: Complete SonarCloud analysis
         env:
