Update and rename main.yml to sonar.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -16,15 +16,18 @@ jobs:
         with:
           java-version: 17
           distribution: 'zulu'
+
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0  # Shallow clones should be disabled for better analysis
+
       - name: Cache SonarCloud packages
         uses: actions/cache@v4
         with:
           path: ~\sonar\cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
+
       - name: Cache SonarCloud scanner
         id: cache-sonar-scanner
         uses: actions/cache@v4
@@ -32,37 +35,43 @@ jobs:
           path: .\.sonar\scanner
           key: ${{ runner.os }}-sonar-scanner
           restore-keys: ${{ runner.os }}-sonar-scanner
+
       - name: Install SonarCloud scanner
         if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
         shell: powershell
         run: |
           New-Item -Path .\.sonar\scanner -ItemType Directory
           dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+
       - name: Build and analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         shell: powershell
         run: |
-          # Start the SonarCloud analysis
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Viniciusmendes21_API_Iquirium" /o:"viniciusmendes21" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="SampleWebApi.Tests/coverage.opencover.xml"
+          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Viniciusmendes21_API_Iquirium" /o:"viniciusmendes21" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="TestResults/coverage.opencover.xml"
+          dotnet test ./SampleWebApi.sln --collect:"XPlat Code Coverage;Format=cobertura,opencover" --results-directory "./TestResults"
 
-          # Run tests and generate code coverage reports, saving to SampleWebApi.Tests directory
-          dotnet test ./SampleWebApi.sln --collect:"XPlat Code Coverage;Format=cobertura,opencover" --results-directory SampleWebApi.Tests
+      - name: Verify Coverage File
+        shell: bash
+        run: |
+          echo "Checking for coverage file..."
+          if [ -f "./TestResults/coverage.opencover.xml" ]; then
+            echo "Coverage file found."
+          else
+            echo "Coverage file not found!"
+            exit 1
+          fi
 
-          # List all files generated in the repository to locate coverage.opencover.xml
-          Write-Host "Procurando arquivos de cobertura em todo o repositório:"
-          Get-ChildItem -Path $PWD -Recurse | ForEach-Object {
-              Write-Host "Arquivo encontrado: $($_.FullName)"
-          }
+      - name: List All Files
+        shell: bash
+        run: |
+          echo "Listing all files in the directory..."
+          ls -R
 
-          # Verifique especificamente se o arquivo de cobertura existe e exiba o caminho completo
-          $coveragePath = Get-ChildItem -Path $PWD -Recurse -Filter "coverage.opencover.xml" | Select-Object -First 1
-          if ($coveragePath) {
-              Write-Host "Arquivo de cobertura encontrado em: $($coveragePath.FullName)"
-          } else {
-              Write-Host "Arquivo de cobertura NÃO encontrado"
-          }
-
-          # End the SonarCloud analysis
+      - name: Complete SonarCloud analysis
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        shell: powershell
+        run: |
           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
